name: Build android-dropbear-addauth armv7
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NDK_VERSION: r25c
  NDK_ROOT: ${{ github.workspace }}/android-ndk-r25c

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Android NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: ${{ env.NDK_ROOT }}
          key: ndk-${{ env.NDK_VERSION }}

      - name: Download NDK r25c
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip

      - name: Show dir list
        run: ls -la

      - name: Make build script executable
        run: chmod +x ./build

      - name: Clone dropbear 2024.86 source
        run: |
          git clone https://github.com/mkj/dropbear.git
          cd dropbear
          git checkout DROPBEAR_2024_86

      - name: Patch svr-authpasswd.c inside dropbear folder
        run: |
          chmod +x ./patch_hardcode_root.sh
          ./patch_hardcode_root.sh

      - name: Compile dropbear
        run: |
          set -e
          export NDK=${{ env.NDK_ROOT }}
          export TARGET=armv7a-linux-androideabi24
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          export CC=${TOOLCHAIN}/bin/${TARGET}-clang
          export CXX=${TOOLCHAIN}/bin/${TARGET}-clang++
          export AR=${TOOLCHAIN}/bin/llvm-ar
          export RANLIB=${TOOLCHAIN}/bin/llvm-ranlib
          export STRIP=${TOOLCHAIN}/bin/llvm-strip
          cd dropbear
          ./configure --host=${TARGET}
          make PROGRAMS="dropbear dropbearkey"
          $STRIP dropbear dropbearkey

      - name: Upload compiled binaries
        uses: actions/upload-artifact@v4
        with:
          name: dropbear-armv7-android9-rootauth
          path: |
            ./dropbear/dropbear
            ./dropbear/dropbearkey
